package com.finlake.common.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum ResponseCode {

    INTERNAL_SERVER_EXCEPTION("1000"),
    BAD_REQUEST("1001"),
    INVALID_FIELD_FACTORY_EXCEPTION("1002"),
    INVALID_JWT_AUTHENTICATION("1004"),
    DATABASE_ACCESS_ERROR("1005"),
    DATA_CONVERSION_ERROR("1006"),
    USER_DOES_NOT_EXIST("1007"),
    INVALID_CREDENTIALS("1008"),
    TOKEN_GENERATION_ERROR("1009"),

    USER_REGISTERED("2000"),
    USER_AUTHORIZED("2001"),
    ALL_USER_FETCHED("2002"),
    USER_ALREADY_EXISTS("2003"),
    FINANCE_ROOM_CREATED("2004"),
    FINANCE_ROOM_FETCHED("2005"),
    ROOM_USER_CREATED("2006"),
    ROOM_USER_FETCHED("2007"),

    UNKNOWN("9999");

    private final String code;
}
